module.exports = [
    'alohamora',
    'nokia',
    'googlewhack',
    'june 22',
    'theeban siva',
    'shaktimaan',
    'toblerone',
    'samuel jackson',
    'la chasse aux papillons extreme',
    'orange juice',
    'oprah',

    'pierre coffin',
    'camdrome',
    'fight club',
    'sarah gregory',
    'olympics',
    'sparrow',
    'no comment',
    'winston churchill',
    'oreo',
    'chimera',

    'bin laden',
    'azkaban',
    'the battle of anghiari',
    'mattoswaltva',
    'search results',
    'pirate ipsum',
    'france',
    'alpenliebe',
    'dan castellaneta',
    '-soh'
];